services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: './bin/rails server'
    envVars:
      - key: postgresql://kin:lzD48qTxER1BtV97vuhkxebO6ihdfq4s@dpg-d34tb195pdvs73b946jg-a/event_db_ybe5
        fromDatabase:
          name: mysite-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # You'll provide this value on Blueprint creation
      - key: WEB_CONCURRENCY
        value: 2 # Recommended default
databases:
  - name: mysite-db
    plan: free